### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by edvinskis** [TU-Delft-DCC/TU-Delft-DCC.github.io#121]
We should rename our default branch from `master` to `main`. 

Afterwards:

- [x] Update any CI/CD pipelines that reference the `master` branch.
- [x] Update documentation that mentions the `master` branch name.

**Comment by edvinskis** [comment]
@mwakok Could you please rename the default branch? I can then update the documentation and workflows.

**Comment by mwakok** [comment]
Default branch is renamed to `main`.

You can update your local clone with:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
