### ISSUE TITLE
Remove system specific build info from the environment.yml to make it OS independent

### ISSUE THREAD

**Issue by niketagrawal** [TU-Delft-DCC/TU-Delft-DCC.github.io#58]
The environment.yml in the master branch can't be used to create a development environment on a Linux PC because the dependencies contain system specific information in the form of a suffix such as `=py37_0...` such as below:

```
dependencies:
  - alabaster=0.7.12=py37_0
  - anyio=3.5.0=py37haa95532_0
 ```
The system specific information got included in the environment.yml file as a result of direct export of the environment from a PC to a file.

Below error was encountered on a Linux PC when a development environment was generated using the current version of environment.yml

```
$ conda env create -f environment.yml

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - sniffio==1.2.0=py37h03978a9_3
  - greenlet==1.1.2=py37hf2a7229_2
  .
  .
  .
```

In order to create reproducible conda development environments across platforms, a minimal conda environment.yml file with only the name of the dependencies and the version number (if applicable) is required,for example,

```
dependencies:
    - python=3.8
    - pip
    - numpy
```

**Comment by mwakok** [comment]
Also, we should update the documentation on updating dependencies.

**Comment by edvinskis** [comment]
Closing this issue, as the guides have been moved to Quarto.
