### ISSUE TITLE
Port backend from JupyterBook to Quarto

### ISSUE THREAD

**Issue by mwakok** [TU-Delft-DCC/TU-Delft-DCC.github.io#98]
Tasks:
- [x] Remove jupyterbook files (`docs/_toc.yml`, `docs/_config.yml`)
- [x] Setup Quarto
- [x] Update `.gitignore`?
- [x] Update `docs/requirements.txt` and `environment.yml`
- [x] Update CI workflow
- [x] Remove/update `build.sh `
- [ ] Update Contributing guide
- [x] Convert Myst syntax to Quarto syntax in each document

Work in branch 98-port-backend-from-jupyterbook-to-quarto

**Comment by mwakok** [comment]
@edvinskis Are there any other things we should consider?

**Comment by edvinskis** [comment]
> @edvinskis Are there any other things we should consider?

Also:

- [ ] Update `README` on GitHub
- [ ] Update `.lycheeignore`

**Comment by manuGil** [comment]
Can I suggest we change the name of the repo, so that we change the name of the domain?
Some suggestions:
- guides-dcc
- dcc-guides
- guides

**Comment by edvinskis** [comment]
> @edvinskis Are there any other things we should consider?

- [ ] Update `.gitignore`
